export enum ROLES {
  ADMIN = "ADMIN",
  SURVEYOR = "SURVEYOR",
  SURVEYEE = "SURVEYEE",
}

export const roleList = [ROLES.ADMIN, ROLES.SURVEYOR, ROLES.SURVEYEE];

export const ROLE_HIERARCHY = {
  [ROLES.ADMIN]: 3,
  [ROLES.SURVEYOR]: 2,
  [ROLES.SURVEYEE]: 1,
};
